### ISSUE TITLE
st_position_load is broken

### ISSUE THREAD

**Issue by supervised** [spedas/bleeding_edge#10]
you can reproduce the issue by running the crib sheet at:

general/examples/crib_tplot_annotation.pro

The error I'm seeing is:

> % Compiled module: ST_POSITION_LOAD.
> HTTP/1.1 301 Moved Permanently
> Content-Type: text/html; charset=iso-8859-1
> Date: Wed, 22 Feb 2023 19:42:19 GMT
> Location: https://stereo.srl.caltech.edu2/Position/ahead/position_ahead_2008_GSE.txt
> Server: Apache/2.4.54 () OpenSSL/1.0.2k-fips
> Content-Length: 282
> Connection: Close
> 
> Permanent redirect to: https://stereo.srl.caltech.edu2/Position/ahead/position_ahead_2008_GSE.txt
> Request Aborted
> % Compiled module: READ_ASC.
> % OPENR: Error opening file. Unit: 100, File: /Users/eric/data/misc/stereo/Position/ahead/position_ahead_2008_GSE.txt
>   No such file or directory
> % Execution halted at: READ_ASC           88 /Users/eric/trunk/general/tools/misc/read_asc.pro
> %                      ST_POSITION_LOAD   70 /Users/eric/trunk/general/missions/stereo/st_position_load.pro
> %                      $MAIN$             55 /Users/eric/trunk/general/examples/crib_tplot_annotation.pro

**Comment by jameswilburlewis** [comment]
Two problems here:
1) the server is sending a bogus redirect URL (with a nonexistent edu2 TLD)
2) The real server is now https-only, which won't work with file_retrieve.  

Should be a straightforward fix if the URL structures haven't changed.

**Comment by jameswilburlewis** [comment]
st_position_load, st_plastic_load, and st_mag_load have been updated with current URLs and with spd_download instead of file_retrieve.
