### ISSUE TITLE
Bz offset in THEMIS-C since Aug 2022

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#109]
From the FGM team:

with the last update of the THC calibration file, we unfortunately introduced a copy-and-paste error for the Bz component dating back from August 2022.

We apologize for this. In the interest of accuracy and to avoid introducing new errors, we ask that you first update the L2 data with the repaired THC calibration file attached to this email.
After the L2 data is updated, we ask Terry to recalculate the Bz offsets for THC from July 2022 (please coordinate on this).
At the end, we update the calibration file for THC with the new and correct Bz offsets.

**Comment by jimm02** [comment]
Cal file is updated, reprocess if finished.
