### ISSUE TITLE
Spacecraft sometimes out of range of orbit plots

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#117]
We need to adjust the ranges of some of the plots, to ensure all spacecraft are visible. Example:

https://themis.ssl.berkeley.edu/summary.php?year=2023&month=11&day=08&hour=0024&sumType=orbit_plusrbsp&type=orbit_plusrbsp

**Comment by clrussell90404** [comment]
This issue has been fixed
