### ISSUE TITLE
MMS EPD EIS, tplot variable for proton flux is missing

### ISSUE THREAD

**Issue by nickssl** [spedas/bleeding_edge#121]
The MMS summary plots script mms_overview_plot.pro, and also the crib mms_version_numbers_crib.pro, try to plot the following tplot variable which is not loaded:

mms1_epd_eis_extof_proton_flux_omni

Perhaps the name of this variable has been changed in the CDF files? The following variable has a similar name: 

mms1_epd_eis_srvy_l2_extof_proton_flux_omni

**Comment by jameswilburlewis** [comment]
Yes, that's right -- there are probably other variables that have been renamed in a similar way in this version of the EPD CDFs.  Python is already using the updated name, so the IDL routines should also be using it.

See also: https://github.com/spedas/bleeding_edge/issues/77
