### ISSUE TITLE
noaa_load_kp isn't working

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#129]
Perhaps they've changed the directory structure on their FTP server?

```
Time range set from 2021-07-17/00:00:00 to 2021-07-18/00:00:00
% Compiled module: STR_ELEMENT.
IDL> noaa_load_kp
% Compiled module: NOAA_LOAD_KP.
% Compiled module: GET_TIMESPAN.
% Compiled module: ROOT_DATA_DIR.
Warning: No Root Data Directory has been defined! Using default: "/Users/jwl/data/" (Which might change in the future!)
To define the Root Data Directory, see documentation in /Users/jwl/spdsoft_trunk/general/misc/root_data_dir.pro
% Compiled module: IS_STRING.
% Compiled module: ARRAY_CONCAT.
% Compiled module: PARSE_URL.
Downloading: ftp://ftp.ngdc.noaa.gov/STP/GEOMAGNETIC_DATA/INDICES/KP_AP/2021
% Compiled module: SPD_NETURL_ERROR2MSG.
Unable to download file:  ftp://ftp.ngdc.noaa.gov/STP/GEOMAGNETIC_DATA/INDICES/KP_AP/2021
FTP Response: 78
FTP Header: 220-                    ----- Notice -----

```

**Comment by nickssl** [comment]
FTP site and directory is correct, but it contains files up to 2018 only. Year 2018 is also incomplete, ends in April.

**Comment by jameswilburlewis** [comment]
When you mentioned the cutoff date of 2018, that jogged my memory....I think this was already a known issue.
There's a /gfz keyword in noaa_load_kp, that uses an alternate server ftp://ftp.gfz-potsdam.de/pub/home/obs/kp-ap/wdc/ .
And that seems to work.   I'm going to change this from a bug to an enhancement request -- if the end date of the time range is after the 2018 cutoff, noaa_load_kp should proceed as if /gfz was set.

**Comment by nickssl** [comment]
Yes, using ftp.gfz-potsdam.de for 2018 or later was an easy fix.
