### ISSUE TITLE
Updated calibration files for THEMIS FGM

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#132]
Adrian P has sent updated calibration files and solar array current spin models, with coverage through the end of October 2023.  It sounds like they might have recalculated some calibrations for earlier time intervals. There was mention at the THEMIS SWT of some discontinuity in the high strength fields that impairs calibration (could this be the known issue with early/late FGM range transmissions and resulting loss of higher order bits in the data values?)

**Comment by jimm02** [comment]
Updated cal and spin_cal files, started reprocess. Will close after reprocess is done.

**Comment by jimm02** [comment]
Reprocess done.
