### ISSUE TITLE
Spin tone in FGL-DSL data when loading multiple days of data

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#156]
Vassilis noticed some spin tone in the calibrated FGL-DSL data for THEMIS-E.   Ferdinand points out that it only appears when loading multiple days of data:

> The spin tone in the DSL Bx and By components seems to be a software problem:
> - If we load the data for the 30th of April, we cannot observe the spin tone in the two components. (timespan, '2024-04-30')
> - If we load the data for several days, the spin tone is visible. (timespan, '2024-04-29‘, 2)
> (see images: no_spin_tone.png and spin_tone.png)

The latest calibration points are for late February, so I'm not sure why the start date of the time interval (April 30 vs April 29) would affect the calibrated results?

![No_Spin_tone](https://github.com/spedas/bleeding_edge/assets/105754292/37659b98-75ac-41b8-a519-dcf8b414c55b)

![Spin_tone](https://github.com/spedas/bleeding_edge/assets/105754292/ebeb19f3-38d8-4a4a-b2a6-f56c7fdc8f62)

**Comment by jimm02** [comment]
I think that what happens here is that the spintone removal process gives results that may be inaccurate if the timespan of the data is too long. Ordinarily, the spintone removal process works in batches, but the batch times are determined by the times in the calibration file. Once we are past the last time in the cal file, then the spintone removal is processed for one big batch, and in this case the second day's spintone removal is wildly off. The differences are typically much less noticeable.
I could put in something that breaks the data into day-long batches if needed after the last cal file entry if needed. What do you all think?
