### ISSUE TITLE
SPEDAS 6.1 release needed

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#157]
We have updated the THEMIS FGM calibration files, which makes them incompatible with older calibration code.   We need to get this change into a SPEDAS 6.1 release ASAP.

Jim M has made a release branch and zip file: 

https://themis.ssl.berkeley.edu/socware/spedas_6_1/spedas_6_1.zip

Please download the zip file and try a few quick tests (especially thm_load_fgm, level=1, type=calibrated) to make sure nothing's broken in your environment, that the version strings are correct, etc.  Assuming everything works, we can upload it to spedas.org and I'll send out a release announcement.

I guess we should do a VM release, too -- Nick, do you know if our old "right to distribute" license still works, or do we now have to switch to the new license and maybe change our build procedures?

**Comment by jameswilburlewis** [comment]
New 6.1 zip file is up, with some small changes to the FGM cal code to be more lenient about extra columns in the cal file.

**Comment by nickssl** [comment]
I did some tests and the license seems to be working. I will go ahead and create the 6.1 VM release.

**Comment by jameswilburlewis** [comment]
There seems to be an issue sending the release announcement to spedas-list@spedas.org.  Looking into it...

**Comment by jameswilburlewis** [comment]
Server reboot seems to have fixed the issue, looks like the mail went out.
