### ISSUE TITLE
Reprocess THEMIS AE index May 10-11 with Alaska stations 

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#163]
From Vassilis:

Can we have the THEMIS AE stations for May 10-11 (large storm) reprocessed to include stations in Alaska since the Kyoto AE shows greater magnitude than THEMIS AE?

**Comment by jameswilburlewis** [comment]
From Vassilis:  There are still discrepancies after adding all the Alaska stations.  We should try reprocessing with just the official AE stations and see what we get.

**Comment by jimm02** [comment]
I reverted the THEMIS AE calculation to remove the extra sites, reprocessed May 10 and 11, and reprocessed the plots.

**Comment by jameswilburlewis** [comment]
Try adding:

College (CMO)
Fort Yukon (FYU)
Barrow (BRW)
Yellowknife (YKC)
