### ISSUE TITLE
ASI plots missing from UCLA mirror site

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#173]
Christine G. was having trouble finding some ASI images at the UCLA mirror.   It seems that there might have been an issue with the UCLA site or mirroring process for the ASI plots.  And Nick noticed that some of the ASI data at Berkeley had not yet been processed to mosaics and movies.

**Comment by nickssl** [comment]
The web pages at Berkeley are working correctly, but the files at UCLA have not been updated yet. Their summary.php page is also an older version. Someone should fix the mirroring procedure.
