### ISSUE TITLE
ASI movies in mpeg format do not play in modern browsers

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#174]
In the past, it was easy to play the ASI movies directly in the browser.    They are in mpeg format, which modern browsers will not play by default -- you have to download the mpeg file and start a player manually.

It might be time to switch to a more browser-friendly format, probably MP4.  We would need to change our ASI pipeline to produce MP4 files directly,  convert the existing mpeg files to mp4, and change the links on the THEMIS web sites to use the MP4 files.

**Comment by nickssl** [comment]
1. Created .mp4 ASI movies for a single day (2023-01-01) using ffmpeg: https://themisbeta.ssl.berkeley.edu/themisdata/thg/l0/asi/2023/01/01/MOVI/

2.  Revamped the ASI-movie section of the summary plots page. Now it plays an .mp4 movie. If this doesn't exist, it plays an .mpg movie (format not supported by most browsers). If neither exists, it shows a message. Also added a link to the ASI movie directory for that day.
https://themis.ssl.berkeley.edu/summary.php?year=2023&month=01&day=01&hour=0024&sumType=asi&type=movie

3. Need to install ffmpeg to a server and reprocess all ASI movies.

**Comment by nickssl** [comment]
ffmpeg was installed, we are now reprocessing the movies.

**Comment by nickssl** [comment]
All movies have been reprocessed. Any modern browser should now be able to play them on the summary plots page, without having to download the file. For example:

https://themis.ssl.berkeley.edu/summary.php?year=2008&month=01&day=01&hour=0024&sumType=asi&type=movie
