### ISSUE TITLE
INTERMAGNET/NRCAN data access

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#176]
From Cindy:

> I should note that we do not have all of the stations that Kyoto is using. We were downloading them from NRCAN. NRCAN recently removed their ftp server in favor of a more secure option. They have a new web service, FDSNWS. I didn't fully understand the details of their new service so I did ask Nick for his input on the best way download the data. He indicated there was a simple script we could create. If okay, I'll work out the details with Nick and get the data downloaded. Then I can reprocess the AE index, summary plots, and AE index site list.

From Nick:

> By the way, I am helping Cindy with Intermagnet. I will create a PHP script to download the data because they have terminated their ftp server, and now the only access we could find is to use their web service page and download data as json. This is a bit similar to what I do for Kompsat, so I think it will not take me too long. I will save the data in a similar format to what the ftp files used to have, so I hope that all the other scripts will work without modification.

**Comment by nickssl** [comment]
The new scripts that download data from the web service were completed. Everything works as expected now.
