### ISSUE TITLE
Web summary plots, cannot click a plot to change plot durations (24-hour, 6-hour, 2-hour plots) on Mac

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#177]
There seems to be an issue on Macs when clicking web summary plots to cycle through the 24-hour, 6-hour, 2-hour probe summary plots.  Nothing happens.   We might have to delve into the client-side Javascript code to see what's happening, and hopefully fix it.

**Comment by nickssl** [comment]
It was a bug in the javascript code. Fixed now.
