### ISSUE TITLE
Fill gaps in L2 products and summary plots due to delayed transfer of telemetry files from the MOC to the SOC

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#193]
Some of the delayed files go back as far as October 15, well outside our 5-day and 10-day windows for L2 and summary plot processing.

It looks like L2 products are fully up to date now, and SPEDAS shows that the gaps are filled (at least for THA Oct 17-18), but online summary plots are still showing gaps.

**Comment by jimm02** [comment]
Gaps are filled, I just kicked off the overplot reprocess..
