### ISSUE TITLE
Download and process full-resolution ASI data from Feb 2023 (possibly earlier?) onward

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#196]
We don't seem to have the most recent full-resolution ASI (ASF) CDFs in /disks/themisdata/thg/l1/asi/SITE .   For site atha, the most recent asf data available is for July 2023, and for fsim, we only have asf through February 2023.  (Thumbnail AST data is more recent)

We need to check if there's more recent data available, and if so, download and process it.

**Comment by nickssl** [comment]
1. We have now implemented a new process that downloads (using wget) the low res and the high res images from Calgary. This has been run for 2023 and for 2024, and we now have all the images in the SSL server for these two years. This new process runs daily to mirror any new images for the current month and the previous month. It also runs 4 times a year to sync with any new images. 

2. We produce the cdfs for high and for low res images at SSL, from the images downloaded from Calgary (at the previous step above). We now have a new process for this job, too. It was run for 2023 and for 2024 and all the missing cdfs have been created, both for high res and low res. 

These two steps are the first two parts of the new ASI processing procedures at SSL. 

The ASI availability page, with links to for all the above files, is here:
https://themis.ssl.berkeley.edu/gmag/asi_list.php?selyear=4000&selmonth=13&smap=on&sinfo=on&seltxt=0
