### ISSUE TITLE
Implementing masking functionality in MMS particle routines

### ISSUE THREAD

**Issue by ericthewizard** [spedas/bleeding_edge#29]
A user is trying to apply custom masks to the DF data to remove the solar wind component from the data. Currently, the only way to do this is to manually modify the routines that return the DF data to turn those bins off. I think we should investigate adding an option to mms_part_getspec and mms_part_slice2d to allow users to apply custom masks like this without kludging the underlying routines.

**Comment by jameswilburlewis** [comment]
Terry Lieu @ UCLA may have some code that does this in a flexible way (i.e. not necessarily centered on 0)
