### ISSUE TITLE
tplot_fill_time_intv routine not rendering properly

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#32]
From Orlando Romeo (oromeo@berkeley.edu):

 I was trying to use the tplot_fill_time_intv routine, but it doesn't appear to work correctly. Shown below, when I use tlimit after plotting a shaded region, the shaded region extends beyond or before the time range set by tlimit.

![TPLOT_CME_ENC13_TIMES_2](https://user-images.githubusercontent.com/105754292/226711611-e1a3a378-1927-47e6-ab07-26bc11c7267e.png)

**Comment by jimm02** [comment]
Fixed, 

jm

**Comment by jameswilburlewis** [comment]
Orlando confirms it works for him now, closing.
