### ISSUE TITLE
Bad request on downloading one-hour resolution OMNI data

### ISSUE THREAD

**Issue by StellarPlasma** [spedas/bleeding_edge#44]
The function "pyspedas.omni.data" works perfectly when downloading high-resolution OMNI data, but it cannot fetch hourly OMNI data correctly.  

For example, I'm trying to download data between 2000/03/01 03:00 and 2000/03/02 03:00 using:
'omni_vars = pyspedas.omni.data(trange=[start_time, end_time], datatype='hourly')'

And this will result in an error message like this:
'06-May-23 15:37:15: Downloading remote index: https://spdf.gsfc.nasa.gov/pub/data/omni/omni_cdaweb/hourly/2000/
06-May-23 15:37:16: No links matching pattern omni2_h0_mrg1hr_20000301_v??.cdf found at remote index https://spdf.gsfc.nasa.gov/pub/data/omni/omni_cdaweb/hourly/2000/'

After checking the website storage, it can be found that the original hourly data are stored as two separate cdf files per year, not one file per month. For the year 2000, the two files are  *omni2_h0_mrg1hr_20000101_v01.cdf* and *omni2_h0_mrg1hr_20000701_v01.cdf*, which leads to the file pattern error. 

I am on the stable version 1.4.32, could this be a real issue or be caused by errors in my inputs?

**Comment by supervised** [comment]
Thanks for the bug report! That's definitely a real issue. 

It looks like there's also a problem loading the hourly files that do exist (omni2_h0_mrg1hr_20000101_v01.cdf and omni2_h0_mrg1hr_20000701_v01.cdf) - when I try to load those, no tplot variables are created.

**Comment by supervised** [comment]
Thanks again for the bug report! These issues should be fixed in v1.4.33.

**Comment by StellarPlasma** [comment]
Thank you for helping to confirm! Looking forward to the future fix!

**Comment by supervised** [comment]
The fix should be available now; run:

`pip install pyspedas --upgrade`

to get the latest version. 

Here's what happens when I run your example using the latest version:

```
import pyspedas

trange = ['2000/03/01 03:00', '2000/03/02 03:00']
omni_vars = pyspedas.omni.data(trange=trange, datatype='hourly')

from pytplot import tplot
tplot('BZ_GSE')
```

![21571449-f917-4286-b623-3545004bb5ef](https://user-images.githubusercontent.com/4745136/236914872-9da5f484-c2a4-4fd0-8999-971ba4c30051.png)

**Comment by StellarPlasma** [comment]
Thank you so much for this quick fix! It works as expected in this version!
