### ISSUE TITLE
Temporarily suspend L2 FGM file production

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#56]
The FGM team is working on improving some of the calibrations (THEMIS-B,-C, and -E spin axis offsets in particular).   They have asked us to suspend L2 CDF production for the time being.  We will make temporary adjustments to the existing calibration files so that calibrating L1 FGM data on the fly will give reasonable results.   This may impact summary plot production or other processing that depends on calibrated FGM data.

**Comment by jimm02** [comment]
Stopped L2 process for THEMIS E FGM, deleted L2 files after 2023-04-27, replaced FGS data with fill values in THEMIS E FIT L2 files, and rpeprocessed files post 2023-04-27. Reprocessed single probe overviews, FGM overviews, FGM wave survey plots after 2023-04-27 using L1 data.
