### ISSUE TITLE
Help request on downloading MMS data mystery

### ISSUE THREAD

**Issue by supervised** [spedas/bleeding_edge#60]
A user is having trouble accessing MMS FPI data, but I'm unable to reproduce the issue locally (I'm able to download the data). We need to provide some steps to help troubleshoot the issue; the command they're using is:

```
tr = ['2016-12-17/10:15:00', '2016-12-17/10:20:00']
mms_load_fpi, trange=tr, datatype= ['dis-moms'], data_rate='brst', /center, level='l2', probe=1, /time_clip
```

<img width="1434" alt="Error Message 1" src="https://github.com/spedas/bleeding_edge/assets/4745136/3be26c52-5072-44de-bc5b-aa4822cf52dd">

**Comment by nickssl** [comment]
Works for me without problems (Windows 11, IDL 8.8.3).

**Comment by supervised** [comment]
> Works for me without problems (Windows 11, IDL 8.8.3).

Thanks for checking!

**Comment by supervised** [comment]
Update: there must be some firewall or /etc/hosts issue; I suggested the user add the /spdf option to grab the data from SPDF instead of the SDC, and now they're able to download data.
