### ISSUE TITLE
Help request on THEMIS twavpol #2 

### ISSUE THREAD

**Issue by ericthewizard** [spedas/bleeding_edge#62]
I received another help request on THEMIS twavpol:

> I want to know when we use the twavpol for the themis probes (b,c). In the tplot, the color bar shows the different parameters of the waves, but I can't figure out what is on the v-axis(as highlighted in the attached figure with red lines). if it's frequency, then why does it only show a range of 0 to 8? but in FFT tplot the frequency range is up to 3000. 
> 
> Please explain to me what parameter is on this axis and whether we can convert it to frequency[Hz].
 
![2021-02-08_TWP-1](https://github.com/spedas/bleeding_edge/assets/4745136/7a55199e-abf2-4266-a26b-67a815f329dd)

**Comment by jameswilburlewis** [comment]
The y-axis is indeed frequencies in Hz.   FGL data for THEMIS-B on this date has a cadence of 16 samples/sec, so the FFT frequency bins cover the range from 0 to the Nyquist frequency = 8 Hz.

The onboard FFT data is collected from the SCM instrument at much higher sample rates, so the frequency range will be correspondingly larger.
