### ISSUE TITLE
flatten_spectra bug with both xrange and yrange options set

### ISSUE THREAD

**Issue by ericthewizard** [spedas/bleeding_edge#65]
A user reported a bug in flatten_spectra: if you set both the xrange and yrange options in flatten_spectra, it says (incorrectly) that there's no data to plot. Specifying xrange or yrange independently work as expected. To reproduce the issue:

```
mms_load_fpi, trange=['2015-10-16/04:00', '2015-10-16/06:00'], datatype='dis-moms'
tplot, ['mms3_dis_energyspectr_omni_fast', 'mms3_dis_energyspectr_px_fast']
flatten_spectra, time='2015-10-16/05:20', xrange=[0, 5e3], yrange=[0, 1e6]
```

**Comment by jameswilburlewis** [comment]
There was a block of code that didn't get run if both xrange and yrange  were set:

```
    if N_ELEMENTS(xrange) ne 2 or N_ELEMENTS(yrange) ne 2 then begin
         ; do stuff to find x and y ranges

```

There is a bit of code later that also checks, seperately, whether xrange or yrange were set, but that code doesn't make sense if the previous code block didn't run.  I removed the "if" and "endif" statements to run it unconditionally, and that seems to have fixed the problem.
