### ISSUE TITLE
Add GMAG stations from MagStar and SMART

### ISSUE THREAD

**Issue by clrussell90404** [spedas/bleeding_edge#90]
Mike Hartinger requested we add gmag stations from MagStar and SMART to the other stations that THEMIS serves

**Comment by jameswilburlewis** [comment]
Apparently the SMART data sits on a Google Drive and has inscrutable file and directory names.   Cindy is looking into some Python code the team provided to access the data, so hopefully this will prove to be a mere inconvenience and not a dealbreaker.

**Comment by clrussell90404** [comment]
MagStar has been added to the other GMAG networks that thmsoc downloads on a daily basis. Scripts have been added to the cronjob that download the csv files to our server and scripts have been added that convert the csv files to CDFs. This issue can be closed.
