### ISSUE TITLE
Update THEMIS FGM calibration through July 2023

### ISSUE THREAD

**Issue by jameswilburlewis** [spedas/bleeding_edge#96]
We've received updated FGM cal files from Johannes Mieth.  They need to be put into production, and affected L2 CDFs reprocessed.

**Comment by jimm02** [comment]
Updated cal files, and reprocessed,  FGM and FIT L2 files for probe A, after 2023-04-29; for probe B, after 2022-11-01; for probe C, after 2022-08-01; for probe D, after 2022-12-02; for probe E, after 2022-12-01
